// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $mail_mail_ from "./routes/mail/[mail].tsx";
import * as $thanks_for_contact from "./routes/thanks-for-contact.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/mail/[mail].tsx": $mail_mail_,
    "./routes/thanks-for-contact.tsx": $thanks_for_contact,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
